### ISSUE TITLE
[BUG] Event survey notification sent at wrong time

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3684] opened 2023-08-31 03:17 UTC
I created an event for 8/31 from 8-8:30am with a survey to send out one hour later at 9:30am. I received a notification to take the survey tonight (8/30 at 10pm). When clicking thru, the survey was not yet available. 

I expect the survey notification to be sent after an event has ended at the time specified in the event admin settings. 

V5.0.57
Android Pixel 6

![Screenshot_20230830-220738.png](https://github.com/rokwire/illinois-app/assets/1044905/d704364c-f5be-4488-89ef-65026fa4a973)

![Screenshot_20230830-220303.png](https://github.com/rokwire/illinois-app/assets/1044905/0335049e-c5d6-4830-9a37-dee97ad97669)

![Screenshot_20230830-220050.png](https://github.com/rokwire/illinois-app/assets/1044905/6c10c82c-caf3-4b97-a4c5-4ea7453abda9)

![Screenshot_20230830-221157.png](https://github.com/rokwire/illinois-app/assets/1044905/e972ecdb-e199-49d6-8a6a-de9bfe4dfeab)

**Comment by pmarkhennessy** [comment] 2023-09-01 00:50
@TodorBachvarov probably a Calendar BB issue, if it is can you create an issue in the correct repo please.

**Comment by TodorBachvarov** [comment] 2023-09-05 13:38
I've created backend issue: https://github.com/rokwire/calendar-building-block/issues/326 and closing this one.

**Comment by TodorBachvarov** [comment] 2023-09-08 11:35
@vburgett, could you retest this issue please, because it seems to work fine now. Also could you also provide the the environment/build name (dev/test/prod). Also could you make sure to not delete the event so we can check the database. Thanks.

**Comment by vburgett** [comment] 2023-09-08 20:06
@TodorBachvarov 

**Event:**
Eat popcorn!
9/8/2023
12pm-1pm CT
Survey set to go out 1 hour after the event ends (an attendee should have received the notification at approximately 2pm CT)

Prijo and I both received a survey notification via Unread/All Notifications within the app at 11am CT on 9/8. This notification was immediately followed when I had set the event to have a survey in the settings. 

Prijo and I received a push notification on our Androids at 2:18pm CT, as anticipated. There was no matching notification in the app. 

I have not deleted this event but it is in the past now. Do you need me to edit it to be in the future in order to troubleshoot?

Illinois app v 5.0.62 dev
Android 13, Pixel 6

**Comment by mdryankov** [comment] 2023-09-18 09:32
@vburgett, I was not able to reproduce the exact issue. In my attempt all rattendees have been linked to a scheduled notification for the survey followup. The push notifications were received near to the planned time as well. 

What I observed as a slightly unexpected result was that the scheduled notification is visible (within the Inbox) before the scheduled time. 

Please confirm the above. If this is what we observe with the current state, then the root cause and the resolution would be different - e.g fix on notifications BB side the visibility of scheduled notifications. 

Thanks, 
Mladen

**Comment by mdryankov** [comment] 2023-09-18 09:55
Linked issue: https://github.com/rokwire/notifications-building-block/issues/166

**Closed** 2024-02-15 04:05 UTC
Labels: Type: Bug
