### ISSUE TITLE
[BUG] Super Events are Broken

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#624] opened 2021-07-27 20:22 UTC
Sub Events are not appearing under their Super Event. Super Events do not display the sub events.
This is true for the latest .apk  2.6.10, as well as the version currently in the stores.

**To Reproduce**
In test:
 Look for the Super Event "Kathryn's Test Move In Week"  event ID 61004fc80298ec000784caf0
 It has 2 sub events "Undergraduate Hall Early Arrival Starts" and "LLC"
  All 3 events have been published in test

To view in the app, choose category "Community" and Next 30 days. The Super event starts on August 15.

See this screenshot shows the super event with no sub events rendered in it. Then separately below it, one of the sub events. 

![Super events](https://user-images.githubusercontent.com/69397705/127221754-433e4837-5406-41a1-acfd-4a2e6114f44a.png)

@sandeep-ps

**Comment by sandeep-ps** [comment] 2021-07-28 04:42
After a little bit of investigation, it looks like that this might be caused by a backend error when getting back sub-events for a super event. I will work with @bingzhang to come up with a fix for this tomorrow.

**Comment by sandeep-ps** [comment] 2021-07-28 21:59
@kpecknold, this is fixed in the DEV instance. Please check. If it looks good, we will release a new version of Events BB and submit it for deployment tomorrow.

**Closed** 2021-11-03 14:56 UTC
Labels: Type: Bug
