### ISSUE TITLE
Course am/pm problem 

### ISSUE THREAD

**Issue by nelshopp** [rokwire/illinois-app#2313] opened 2022-08-22 18:40 UTC
In Academics - My Courses section of the app, FSHN 120 is showing as 12:30am instead of 12:30pm
![courses](https://user-images.githubusercontent.com/91676531/185994870-7233b9ee-879b-4a0d-8730-87e39e1c7daf.jpg)
![courses1](https://user-images.githubusercontent.com/91676531/185994891-ca2f2d7e-3577-4670-98d2-838e9f74306c.png)

**Comment by mihail-varbanov** [comment] 2022-08-25 14:17
Closing this issue as a duplicate of #2310.

**Closed by mihail-varbanov** 2022-08-25 14:17 UTC
Labels: Type: Bug
