### ISSUE TITLE
[BUG] My Big 10 Events Favorite widget: starred events and teams filter not aligning

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3986] opened 2024-02-18 18:24 UTC
1. I have the wrestling event "Illinois at Northwestern" today at 2pm CT starred
2. Under Favorites, the "Illinois at Northwestern" card appears in the "My Big 10 Events" widget
3. When I tap on the widget's "View All" link, I do not see that event (my teams setting has "Men's Wrestling" checked)

Version 5.1.29 prod
Android 14, Pixel 6

https://github.com/rokwire/illinois-app/assets/1044905/8f65fb29-a67a-4e7d-b284-f581e9fd3d79

**Comment by dobromirdobrev** [comment] 2024-02-19 13:39
@vburgett ,

We were not able to reproduce this issue. There is no such event anymore (as it is passed). So I tried with another event from "Women's Basketball" -> "Indiana at Illinois" - all worked as expected. Please see the attached screen recording:

https://github.com/rokwire/illinois-app/assets/5978121/57969d09-71e8-4288-8fcf-adbac315a0aa

Could you please give us more details or a stable user scenario in which we could reproduce this behavior?

Have you tried with another event? Does it appear still? Any additional information will be very helpful. 

Thanks.

**Comment by vburgett** [comment] 2024-02-19 15:41
@dobromirdobrev 
**Step-by-step user scenario**
1. Go to Browse > Events > All Events
2. Sort by "Big 10 Athletics" and "**Wrestling**"
3. Star "Illinois at Big 10 Championships" on Mar 9
4. Go to Favorites > My Big 10 Events widget
5. See starred card for the event "Illinois at Big 10 Championships" on Mar 9
6. Tap on it
7. See event details panel is not starred
8. Go back to Favorites > "My Big 10 Events"
9. Tap "View All" 
10. Confirm that "**Men's Wrestling**" is selected under Teams
11. See how the "My Big 10 Events" panel still says "There are no starred events for the selected team."

I think this issue is specific to wrestling. Is it because "Wrestling" under event Filters does not match "Men's Wrestling" under Teams?

**Expectations**
Step 7: event detail panel should display an orange star
Step 11: the "Illinois at Big 10 Championships" on Mar 9 should display 

Version 5.1.29 prod
Android 14, Pixel 6

**Comment by dobromirdobrev** [comment] 2024-02-22 07:07
This is fixed in version 5.1.33 and 5.2.0

**Comment by vburgett** [comment] 2024-10-22 04:04
Confirming as complete in 6.1.13. Thank you!

**Closed** 2024-10-22 04:04 UTC
Labels: Type: Bug
