### ISSUE TITLE
[BUG] Adding event attendance takers not working

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3656] opened 2023-08-28 17:29 UTC
Under Event Attendance, I added multiple netids and then a single netid. Those individuals did not get attendance taker access to my event, "event registration in 5.0.55." I also received the error in the below screenshot.

I expect to enter multiple netids under Event Attendance > NetIDs for additional attendance takers, have those settings save, and have those individuals see "Take Attendance" on that event's detail panel. 

V5.0.55
Android Pixel 6

![Screenshot_20230828-121345~2.png](https://github.com/rokwire/illinois-app/assets/1044905/ced71606-2d9f-4b4f-bb86-3241b105013a)

![Screenshot_20230828-114915~2.png](https://github.com/rokwire/illinois-app/assets/1044905/662d0c50-a295-47a9-b0dc-8260675058dc)

![Screenshot_20230828-115747~2.png](https://github.com/rokwire/illinois-app/assets/1044905/283ff7b9-bfa6-44c3-9135-4028a760f134)

**Comment by dobromirdobrev** [comment] 2023-08-30 11:35
Hi @vburgett ,
Currently I'm unable to reproduce the problem - I managed to add additional attendance takers successfully. Could you please check once again with the latest app version 5.0.58? I assume that this was a temporary backend issue which is now fixed and working. If you still observe that behaviour, please let us know. Thanks cc @pmarkhennessy

**Comment by vburgett** [comment] 2023-09-05 21:54
There are three locations to enter additional attendance takers on the event details panel. 

Adding a NetID to any of the three locations does _not_ result in the individual having access to the event to take attendance. The three locations are:

Event Admin Settings > Event Attendance (saves names but does not give the people access to "Take Attendance")
Event Admin Settings > Edit Event > Event Attendance (saves names but does not give the people access to "Take Attendance")
Take Attendance (can enter NetIDs but does not save)

![Screenshot_20230905-164448](https://github.com/rokwire/illinois-app/assets/1044905/be2791bf-0028-475e-9f6a-bd37e3250cb3)

![Screenshot_20230905-164416](https://github.com/rokwire/illinois-app/assets/1044905/e7791449-71c7-4816-8c22-9b93e107f940)

![Screenshot_20230905-120415](https://github.com/rokwire/illinois-app/assets/1044905/239cb563-dccd-4180-8324-a28b7960fb1c)

**Comment by vburgett** [comment] 2023-09-05 22:00
I'm testing off of the event VB on 9/8 at 4pm.

**Comment by dobromirdobrev** [comment] 2023-09-13 13:00
Hi @vburgett ,

This issue has 3 different problems. 

1. An "Attendance taker" does not see "Take attendance" button in event detail panel.
This was a bug in the app and it was fixed.

2. An admin adds new attendance taker NetId from Event -> Event Admin Settings -> Edit Event -> Event Attendance. 
There is no error here but the user with the specified NetID does not get "promoted" to attendance taker. That's why one does not see "Take Attendance" button. In this case the backend service (Calendar BB) does not acknowledge the changes for attendance takers. 
The solution here was to hide "Event Attendance" section when modifying an event. So the admin can update the event attendance from Event -> Event Admin Settings -> Event Attendance.

3. An admin adds new attendance taker NetID from Event -> Event Admin Settings -> Event Attendance and the app shows error. 
This is because the backend service (Calendar BB) does not allow a user with netid to be added as attendance taker if he already is and admin or registrant (e.g. the user can have only one event role, either "admin", "participant" or "attendance-taker"). 
Here the solution was to add validation before applying the changes. So if a user is in the registrant list (as admin or participant), he cannot be added via the additional attendance takers netids field. A relevant message is shown to the admin in that case.

4*. The one that you mentioned (e.g. with the label "Add NetID to the guest list"):

Take Attendance (can enter NetIDs but does not save)

It is for something different - for adding users to the guest list (e.g. mark a netid as "participant"). I double checked that and all worked as expected - the user is added to the guest list. Please note that this is not for attendance takers.

All of these changes are applied in version 5.0.66. Please verify them and let us know if you have any questions or comments. 

cc @pmarkhennessy

**Comment by mihail-varbanov** [comment] 2023-09-15 11:54
1. I undid point 2 from the above [comment](https://github.com/rokwire/illinois-app/issues/3656#issuecomment-1717586857) "The solution here was to hide "Event Attendance" section when modifying an event. So the admin can update the event attendance from Event -> Event Admin Settings -> Event Attendance." and opened an issue in Calendar BB for this: rokwire/calendar-building-block#355

2. I undid point 3 from the above [comment](https://github.com/rokwire/illinois-app/issues/3656#issuecomment-1717586857) "Here the solution was to add validation before applying the changes. So if a user is in the registrant list (as admin or participant), he cannot be added via the additional attendance takers netids field." and opened an issue in Calendar BB for this: rokwire/calendar-building-block#356

No updates will be performed on UIUC client until we get a clear notice that there are good reasons why this should not be done on the backend. @pmarkhennessy, please take a stand on this matter.

**Comment by mihail-varbanov** [comment] 2023-09-18 09:03
**Re: University Monday 2023/09/11** / 2023-09-15

MV: This is a long story and I will try to explain it briefly. All problems mentioned in this issue appear to be backend problems.
 
1\. Update event API fails to modify the attendees list. The resolution is to fix it on the backend, as it currently works fine in the PUT event/{eventId}/attendance API. This is an issue [#355](https://github.com/rokwire/calendar-building-block/issues/355).

2\. Calendar BB fails to set as an attendance taker a user that is already registered for this event. I believe in real life that it is permissible for an event registrant to also be an attendance taker. The problem is in the Calendar BB's model that assumes that a user can be either admin, participant (registrant) or attendance taker and not a combination of these. The same problem appears in [#3619](https://github.com/rokwire/illinois-app/issues/3619) but for admin and attendance takers roles. That's why I created ​​[#356](https://github.com/rokwire/calendar-building-block/issues/355) in Calendar BB's for this.

Possible solutions:

2.1. Update the user role model in Calendar BB to handle multiple roles for a user. I guess this should be hard and risky before the release.

2.2. Switch between participant and attendance taker roles instead of fail. The problem is that this user will not be in the participants list any more.

2.3. Leave it as now and say that a participant is forbidden to be an attendance taker. Maybe the Calendar BB should provide a more meaningful response than "error performing transaction". We can also think of performing some preprocessing in the UIUC client in order to handle this case and provide more user friendly UX.

I assigned this issue back to you as my belief is that you should take a decision which way to go.

**University Monday 2023/09/18** / 2023-09-18

4.1 [BUG] Adding event attendance takers not working, https://github.com/rokwire/illinois-app/issues/3656

MH: Yes Misho let us "Leave it as now and say that a participant is forbidden to be an attendance taker."

Basing on the above thread it is not possible to switch from event participant/registrant to attendance taker and an attempt to do so will fail as it currently does.

**Closed** 2024-02-15 04:05 UTC
Labels: Type: Bug
