### ISSUE TITLE
[BUG] Some Game Day Guides return 404 error

### ISSUE THREAD

**Issue by nelshopp** [rokwire/illinois-app#1531] opened 2022-04-08 18:36 UTC
Hi Team, 
When tapping on Game Day Guide for a specific athletic event OTHER than men's basketball or football will return a 404 error.    

**To Reproduce**
1. Tap on Athletics
2. Tap on "Tennis" under "Women's Sports"
3. Tap on "Purdue at Illinois Today at 1pm"
4. Tap Game Day Guide

The 404 error then appears

This is inconsistent.  Some events may not have GameDay Guide button or link.  

 - OS: I have reproduced this on Android 12 and 8.  I assume it holds true for iOS as well. 
 
 - Version 3.2.37
![tennis](https://user-images.githubusercontent.com/91676531/162501372-e7bde31e-c4fd-4633-ab3f-61ed44606f89.jpg)
![404](https://user-images.githubusercontent.com/91676531/162501375-7b1a2621-7a43-47b9-a7eb-0a622c010f80.jpg)

**Comment by nelshopp** [comment] 2022-04-08 18:41
Interestingly, the upcoming men's tennis match does not have Game Day Guide button or link.

**Comment by nelshopp** [comment] 2022-04-08 18:44
FYI... According to the Asst. Director of Communications of the DIA, "The only sports that have Gameday Guides are men’s basketball and football."

**Comment by dobromirdobrev** [comment] 2022-04-11 13:11
Hi @nelshopp ,

What should be the expected behavior here? 

Since:

> The only sports that have Gameday Guides are men’s basketball and football.

then should we remove the "Game Day Guide" for the other sports?
Please, let us know. Thanks. cc @pmarkhennessy

**Comment by nelshopp** [comment] 2022-04-11 13:27
Expected behavior:
Button and links  for the Game Day Guides should only exist for men’s basketball and football.

They should not for other sports until they are created.

Thanks!

Tom

From: Dobromir Dobrev ***@***.***>
Date: Monday, April 11, 2022 at 8:12 AM
To: rokwire/illinois-app ***@***.***>
Cc: Nelshoppen, Thomas Peter ***@***.***>, Mention ***@***.***>
Subject: Re: [rokwire/illinois-app] [BUG] Some Game Day Guides return 404 error (Issue #1531)

Hi @nelshopp<https://urldefense.com/v3/__https:/github.com/nelshopp__;!!DZ3fjg!tFCmWpjp7uOn2NS1XkP6DmZSZSi6gEw2BupxcdiD4hFDpJUhwGGSDcznialHzMf5xUs$> ,

What should be the expected behavior here?

Since:

The only sports that have Gameday Guides are men’s basketball and football.

then should we remove the "Game Day Guide" for the other sports?
Please, let us know. Thanks. cc @pmarkhennessy<https://urldefense.com/v3/__https:/github.com/pmarkhennessy__;!!DZ3fjg!tFCmWpjp7uOn2NS1XkP6DmZSZSi6gEw2BupxcdiD4hFDpJUhwGGSDcznialHxS0BDyg$>

**Comment by dobromirdobrev** [comment] 2022-04-12 13:20
Fixed in version 3.3.15

**Comment by nelshopp** [comment] 2022-04-13 15:07
Thanks, @dobromirdobrev!  After testing with v. 3.3.15 apk, I have not been able to replicate the problem.  

Before closing, I'd like @joegrohens to test since he originally found this issue.  

Tom

**Comment by joegrohens** [comment] 2022-04-13 22:59
I have also checked the Athletics events in 3.3.15.apk. I believe the problem is resolved.

**Comment by joegrohens** [comment] 2022-04-13 22:59
@nelshopp ^^^

**Closed** 2022-04-14 13:35 UTC
Labels: Type: Bug
